import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Kylix | Homepage",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="min-h-screen flex flex-col bg-gray-100 text-gray-900">
                    <Header />
                    <div className="flex-grow">{children}</div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
